### ISSUE TITLE
移动硬盘挂载问题

### ISSUE THREAD

**Issue by woni928** [kizimirua/NEWIFI-D2-LEAN-OP#4]
您的固件samba4在window下无法看到目录 更换samba 就可以。
另外大神，我也用的是lean的源码编译的D2 固件，为什么无法挂载到移动硬盘，您是怎么操作的，选取了那些驱动，恳请您告知下，谢谢了！

**Comment by kizimirua** [comment]
请参考此篇教程配置samba：https://gist.github.com/lanceliao/b21cc1b54236c6eadfbb，考虑到samba不容易配置，下个版本会重新加会FTP服务器；关于硬盘挂载问题，需要在编译的时候去Extra packages目录下勾选automount方能支持主流文件系统的挂载，另外如果移动硬盘功率过大，可能需要外接供电才能正常使用

**Comment by woni928** [comment]
测试两个移动硬盘， 一个是2.5寸移动硬盘， 一个是3.5寸的硬盘盒子并外接供电，编译的时候是勾选了automount。但编译出来就是无法挂载移动硬盘，U盘都可以。所以好无奈，前来求助！！！

**Comment by kizimirua** [comment]
那你就是没把驱动编译进去，按照上文给你的方法勾选驱动就行了
