### ISSUE TITLE
問題請教

### ISSUE THREAD

**Issue by aaronchin** [kizimirua/NEWIFI-D2-LEAN-OP#6]
您好 我一樣用LEAN的源碼編譯但是做出來的固件卻會出現找不到2.4G無線的狀況 請問您在編譯的時候有針對MT7603E的驅動或是有做其他不同的設定嗎

**Comment by kizimirua** [comment]
没有，驱动层面都是默认设置，没有任何修改

aaronchin <notifications@github.com>于2020年4月16日 周四15:02写道：

**Comment by aaronchin** [comment]
謝謝
